spring:
  #datasource:
  #url: jdbc:mysql://192.168.200.146:3308/db_test1?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
      #username: sa
      #password: 11111
      # driver-class-name: com.mysql.cj.jdbc.Driver
      #hikari:
  #minimum-idle: 5
      #maximum-pool-size: 15
      # auto-commit: true
      #idle-timeout: 30000
      #max-lifetime: 30000
      #connection-timeout: 30000
      #connection-test-query:  SELECT 1
      #pool-name: hikariCP
  redis:
    host: 192.168.170.230
    port: 6379
    timeout: 10000
    password: Infra5_Gep0int
    database: 1
    jedis:
      pool:
        max-wait: 30000
        max-active: 100
        max-idle: 20
        min-idle: 0
  cache:
    type: REDIS
    cache-names: redisdemopro
    redis:
      #自定义缓存时间
      time-to-live: 60000
      #允许保存空值
      cache-null-values: true
      #禁用前缀
      use-key-prefix: true
      #自定义前缀
      key-prefix:

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

sharding:
  jdbc:
    datasource:
      names: ds0
      # 数据源ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.200.146:3308/db_test1?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
        username: sa
        password: 11111
    config:
      sharding:
        props:
          sql.show: true
        tables:
          t_user: #t_user表
            key-generator-column-name: id  #主键
            actual-data-nodes: ds0.t_user${0..1}    #数据节点,均匀分布
            table-strategy: #分表策略
              inline: #行表达式
                sharding-column: sex
                algorithm-expression: t_user${sex % 2}  #按模运算分配






